entries/forms.py
import wtforms
from wtforms import validators
from models import Entry, Tag

class TagField(wtforms.StringField):
    def _value(self):
        if self.data:
            return ','.join([tag.name for tag in self.data])
        return ''

    def get_tags_from_string(self, tag_string):
        raw_tags = tag_string.split(',')
        tag_names = [name.strip() for name in raw_tags if name.strip()]
        existing_tags = Tag.query.filter(Tag.name.in_(tag_names))
        new_names = set(tag_names)-set([tag.name for tag in existing_tags])
        new_tags=[Tag(name=name) for name in new_names]
        return list(existing_tags)+new_tags

    def process_formdata(self, valuelist):
        if valuelist:
            self.data = self.get_tags_from_string(valuelist[0])
        else:
            self.data = []

class EntryForm(wtforms.Form):
    title = wtforms.StringField('Title', validators=[validators.DataRequired()])
    body = wtforms.TextAreaField('Body', validators=[validators.DataRequired()])
    status = wtforms.SelectField(
        'Entry status',
        choices=(
            (Entry.STATUS_PUBLIC, 'Public'),
            (Entry.STATUS_DRAFT, 'draft'),
        ),
        coerce=int
    )
    tags = TagField('Tags', description='Separate multiple tags with commas')

    def save_entry(self, entry):
        self.populate_obj(entry)
        entry.generate_slug()
        return entry

class ImageForm(wtforms.Form):
    file = wtforms.FileField('Image file')

class CommentForm(wtforms.Form):
    name = wtforms.StringField('Name', validators=[ validators.DataRequired()])
    email = wtforms.StringField('Email', validators=[validators.DataRequired(), validators.Email()])
    url = wtforms.StringField('Url', validators=[ validators.Optional(), validators.URL()])
    body = wtforms.TextAreaField('Comment', validators=[validators.DataRequired(), validators.Length(min=10, max=3000)])
    entry_id = wtforms.HiddenField(validators=[validators.DataRequired()])

    def validate(self):
        if not super(CommentForm, self).validate():
            return False
        entry = Entry.query.filter((Entry.status == Entry.STATUS_PUBLIC) & (Entry.id == self.entry_id.data.first()))
        if not entry:
            return False
        return True

entries/blueprint.py
import os
from flask import Blueprint, flash, render_template, request, redirect, url_for, g
from flask.ext.login import login_required
from werkzeug import  secure_filename
from models import Entry, Tag
from helpers import object_list
from entries.forms import EntryForm, ImageForm, CommentForm
from app import app, db

entries = Blueprint('entries', __name__,
                    template_folder='templates')


@entries.route('/')
def index():
    entries = Entry.query.order_by(Entry.created_at.desc())
    return entry_list('entries/index.html', entries)


@entries.route('/image-upload/', methods=['GET', 'POST'])
@login_required
def image_upload():
    if request.method == 'POST':
        form = ImageForm(request.form)
        if form.validate():
            image_file=request.files['file']
            filename = os.path.join(app.config['IMAGES_DIR'],  secure_filename(image_file.filename))
            image_file.save(filename)
            flash('Saved %s' % os.path.basename(filename), 'success')
    else:
        form = ImageForm()
    return render_template('entries/image_upload.html', form = form)


@entries.route('/tags/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first_or_404()
    entries = tag.entries.order_by(Entry.created_at.desc())
    return entry_list('entries/tag_detail.html', entries, tag=tag)

@entries.route('/tags/')
def tag_index():
    tags = Tag.query.order_by(Tag.name)
    return entry_list('entries/tag_index.html', tags)


@entries.route('/create/', methods=['GET', 'POST'])
@login_required
def create():
    if request.method == 'POST':
        form = EntryForm(request.form)
        if form.validate():
            entry = form.save_entry(Entry(author = g.user))
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" created successfully.' % entry.title, 'success')
            return redirect(url_for('entries.detail', slug=entry.slug))
    else:
        form = EntryForm()
    return render_template('entries/create.html', form=form)


@entries.route('/<slug>/edit/', methods=['GET', 'POST'])
@login_required
def edit(slug):
    entry = get_entry_or_404(slug, author=g.user)
    if request.method == 'POST':

        form = EntryForm(request.form, obj=entry)
        if form.validate():
            entry = form.save_entry(entry)
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" has been saved.' % entry.title, 'success')
            return redirect(url_for('entries.detail', slug=entry.slug))
    else:
        form = EntryForm(obj=entry)

    return render_template('entries/edit.html', entry=entry, form=form)


@entries.route('/<slug>/delete/', methods=['GET', 'POST'])
@login_required
def delete(slug):
    entry = get_entry_or_404(slug, author = g.user)
    if request.method == 'POST':
        entry.status = Entry.STATUS_DELETED
        db.session.add(entry)
        db.session.commit()
        db.session.commit()
        flash('Entry "%s" has been deleted.' % entry.title, 'success')
        return redirect(url_for('entries.index'))
    return render_template('entries/delete.html', entry=entry)


@entries.route('/<slug>')
def detail(slug):
    entry = Entry.query.filter(Entry.slug == slug).first_or_404()
    form = CommentForm(data = {'entry_id':entry.id})
    return render_template('entries/detail.html', entry=entry, form = form)


def entry_list(template, query, **context):
    query = filter_status_by_user(query)
    valid_statuses = [Entry.STATUS_PUBLIC, Entry.STATUS_DRAFT]
    query = query.filter(Entry.status.in_(valid_statuses))

    search = request.args.get('q')
    if search:
        query = query.filter(Entry.body.contains(search) | Entry.title.contains(search))
    return object_list(template, query, **context)


def get_entry_or_404(slug, author = None):
    valid_statuses = [Entry.STATUS_PUBLIC, Entry.STATUS_DRAFT]
    query =  Entry.query.filter(Entry.slug == slug)
    if author:
        query = query.filter(Entry.author == author)
    else:
        query.filter_status_by_user(query)
    return query.first_or_404()

def filter_status_by_user(query):
    if not g.user.is_authenticated:
        return query.filter(Entry.status == Entry.STATUS_PUBLIC)
    else:
        return query.filter((Entry.author == g.user) & (Entry.status != Entry.STATUS_DELETED))

templates/entries/base_entries.html
{% extends "base.html" %}
{%  block sidebar %}
    <form class="form-inline well" method="get" role="form">
        <div class="input-group">
            <input class="form-control input-xs" name="q" placeholder="search..." value="{{  request.args.get('q', '')}}" />
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Go</button>
            </span>
        </div>
    </form>
{%  endblock %}
{%  block content %}
{%  include "includes/list.html" %}
{%  endblock %}

templates/entries/create.html
{%  extends "base.html" %}
{%  from "macros/form_field.html"  import form_field %}

{% block title %}Create new entry{%  endblock %}
{% block content_title %}Create new entry{%  endblock %}
{%  block content %}
    <form action="{{ url_for('entries.create') }}" class="form form-horizontal" method="post">
        {% for field in form %}
            {{  form_field(field) }}

        {%  endfor %}
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-default">Create</button>
                <a class="btn" href="{{ url_for('entries.index') }}">Cancel</a>

            </div>
        </div>
    </form>
{% endblock %}

templates/entries/delete.html
{%  extends "base.html" %}
{%  block title %}{{  entry.title }}{%  endblock %}
{%  block content_title %}{{  entry.title }}{%  endblock %}
{%  block content %}
    <form action="{{  url_for('entries.delete', slug=entry.slug) }}" method="post">
        <fieldset>
            <legend>Delete this entry?</legend>
            <button class="btn btn-danger" type="submit">Delete</button>
            <a class="btn" href="{{  url_for('entries.detail', slug =entry.slug) }}">Cancel</a>
        </fieldset>

    </form>
{%  endblock %}

templates/entries/detail.html
{%  extends "base.html" %}
{% block title %}{{ entry.title }}{%  endblock %}
{% block content_title %}{{ entry.title }}{%  endblock %}
{%  block sidebar %}
    <ul class="well nav nav-list">
        <li><h4>Tags</h4></li>
        {%  for tag in entry.tags %}
                <li><a href="{{ url_for('entries.tag_detail', slug = tag.slug) }}">{{ tag.name }}</a></li>
        {% endfor %}
    </ul>
    <p>Published {{  entry.created_at.strftime('%m %d/%Y') }}</p>
    {%  if entry.author==g.user %}
        <li><h4>Actions</h4></li>
        <li></li><a href="{{  url_for('entries.edit', slug=entry.slug) }}">Edit</a></li>
        <li></li><a href="{{  url_for('entries.delete', slug=entry.slug) }}">Delete</a></li>
    {% endif %}

{%  endblock %}
{%  block content %}
    {{ entry.body }}
    <h4 id="comment-form">Submit a comment</h4>
    {%  include "entries/includes/comment_form.html" %}
{%  endblock %}

templates/entries/edit.html
{%  extends "base.html" %}
{%  from "macros/form_field.html"  import form_field %}

{% block title %}Edit{%  endblock %}
{% block content_title %}Edit{%  endblock %}
{%  block content %}
    <form action="{{ url_for('entries.edit', slug=entry.slug) }}" class="form form-horizontal" method="post">
        {% for field in form %}
            {{  form_field(field) }}

        {%  endfor %}
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-default">Save</button>
                <a class="btn" href="{{ url_for('entries.detail', slug=entry.slug) }}">Cancel</a>

            </div>
        </div>
    </form>
{% endblock %}

templates/entries/image_upload.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}
{%  block title %}Upload an image{%  endblock %}
{%  block content_title %}Upload an image{%  endblock %}
{%  block content %}
    <form action="{{  url_for('entries.image_upload') }}" enctype="multipart/form-data" method="post">
    {%  for field in form %}
        {{  form_field(field) }}
    {%  endfor %}
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-default">Upload</button>
            <a class="btn" href="{{ url_for('entries.index') }}">Cancel</a>

        </div>

    </div>

    </form>
{%  endblock %}

templates/entries/index.html
{%  extends "entries/base_entries.html" %}
{%  block title %}Entries{%  endblock %}
{%  block content_title %}Entries{%  endblock %}
{%  block content %}
    {% include "includes/list.html" %}
    {%  include "includes/page_links.html" %}
{%  endblock %}

templates/entries/tag_detail.html
{%  extends "entries/base_entries.html" %}

{% block title %}{{ tag.name }}{%  endblock %}
{% block content_title %}{{ tag.name }} entries {%  endblock %}

{%  block content %}
    {%  include "includes/list.html" %}
    {%  include "includes/page_links.html" %}
{%  endblock %}

templates/entries/tag_index.html
{%  extends "base.html" %}

{%  block title %}Tags{% endblock %}
{%  block content_title %}Tags{% endblock %}

{%  block content %}
    <ul>
    {%  for tag in object_list.items %}
        <li><a href="{{  url_for('entries.tag_detail', slug=tag.slug)}}">{{ tag.name }}</a></li>
    {%  endfor %}
    </ul>

{%  endblock %}